---
- name: Enable Consul as a systemd service
  systemd:
    name: 'consul.service'
    daemon_reload: yes
    enabled: yes
    force: yes
  become: yes
  become_user: root

- name: Start service Consul
  systemd:
    name: 'consul.service'
    state: restarted
  become: yes
  become_user: root
